module.exports = {
  USERS: '/',
  USER_ID: '/:id',
  USERS_BASE: '/users',
  PRODUCTS: '/',
  PRODUCT_ID: '/:id',
  PRODUCTS_BASE: '/products',
  PURCHASES: '/',
  PURCHASE_ID: '/:id',
  PURCHASES_BASE: '/purchases',
  REGISTER: '/register',
  LOGIN: '/login',
  AUTH_BASE: '/auth',
  LOCKERS: '/',
  LOCKER_ID: '/:id',
  LOCKERS_BASE: '/lockers',
  AVAILABLE_LOCKERS_BASE:'/available-lockers',
  AVAILABLE_LOCKERS: '/',
  AVAILABLE_LOCKER_ID: '/:id',
};
