module.exports = {
  USERS: '/',
  USER_ID: '/:id',
  USERS_BASE: '/users',
  PRODUCTS: '/',
  PRODUCT_ID: '/:id',
  PRODUCTS_BASE: '/products',
  PURCHASES: '/',
  PURCHASE_ID: '/:id',
  PURCHASES_BASE: '/purchases',
  REGISTER: '/register',
  LOGIN: '/login',
  AUTH_BASE: '/auth',
  REFRESH: '/refresh',
  LOGOUT: '/logout',
  LOCKERS: '/',
  LOCKER_ID: '/:id',
  LOCKERS_BASE: '/lockers',
  AVAILABLE_LOCKERS_BASE: '/available-lockers',
  AVAILABLE_LOCKERS: '/',
  AVAILABLE_LOCKER_ID: '/:id',
  HOME: '/',
  ADD_TO_CART: '/:id/add-to-cart',
  REMOVE_FROM_CART: '/:id/remove-from-cart',
  USER_CART: '/cart',
};
